#print("Hello World!")
#print("Hello Again")
#print("I like typing this.")
#print("This is fun.")
#print('Yay! Printing.')
#print("I'd much rather you 'not'.")
print('I "said" do not touch this.')
print("I'll touch whatever the fuck I want thank you very much :D")
